#workspace 'JuCamera.xcworkspace'

# public specs
# source 'https://github.com/Cocoapods/Specs.git'
# source 'http://code.paic.com.cn/iosmodules/paspec.git'

platform :ios, '9.0' 
#inhibit_all_warnings!

target 'JuCamera' do
     pod 'JuCamera', :path => '../'
end



